<html>
    <title>LEMS | Front</title>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl('/css/front.css')); ?> 
    <body>
        <div class="main">
            <div id="header">
                <div id="menu_main">
                  <ul id="menu">
                      <li><a href="#">Home</a></li>
                      <li>
                          <a href="#">Categories</a>
                          <ul>
                              <li><a href="#">CSS</a></li>
                              <li><a href="#">Graphic design</a></li>
                              <li><a href="#">Development tools</a></li>
                              <li><a href="#">Web design</a></li>
                          </ul>
                      </li>
                      <li><a href="#">Work</a></li>
                      <li><a href="#">About</a></li>
                      <li><a href="#">Contact</a></li>
                  </ul>  
                </div>
                
            </div>
            <div class="bodypart">
                <div id="leftbody">left body</div>
                <div id="bodycontent">
                    <?php echo $this->layout()->content; ?>
                </div><!--end of bodycontent-->
                <div id="rightbody">right body</div>
            </div><!--end of bodypart-->
            <div id="clear"></div>
            <div id="footer">
                &COPY; Copyright 2013, All Rights Reserved
            </div><!--end of footer-->
        </div><!--end of main-->
    </body>
</html> 