<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Leapfrog Employee Management System</title>
<link href="front.css" rel="stylesheet" type="text/css" />
</head>
<div id="container_wrapper">
	<div class="spacer"></div>
<div id="container">
<div id="top"><a href=''>Logout</a></div>
  <div id="header">
      <div id="inner_header">
        <div id="site_title">Leapfrog Employee Management System</div>
          <div id="site_slogan">Version 1.0</div>
      </div>
  </div>