<!DOCTYPE html>
<head>
 <?php echo $this->headLink()->prependStylesheet($this->baseUrl('/css/style.css')); ?> 
   
</head>

<body>

<div id="header">
	<div id="title">
		<div id="logo">
			<img src="/images/style/logo.png" alt="logo">
                        EMS
		</div>
    

	</div>
</div>	
<div id="navigation-menu">
    <div id="menu">
            <!--start -->

        <div id="nav">
            <ul>
              <li class="first">
               <a href="#">Home</a>

              </li>
              <li>
                <a href="#">Login</a>
              </li>
              <li>
                <a href="/front/index/about">About</a>
               </li>


            </ul>
        </div>

    </div>  
        <!-- end-->	
</div>
   
<div id="inner-container">
       
         
            
        <?php echo $this->layout()->content; ?>

 
</div>
<div style="clear:both;"></div>
    

<div id="copyright">&copy; Leapfrog Technology Inc.</div>


</body>
</html>
        