<!DOCTYPE html>
<head>
 <?php echo $this->headLink()->prependStylesheet($this->baseUrl('/css/style.css')); ?> 
   
</head>

<body>

<div id="header">
	<div id="title">
		<div id="logo">
			<img src="/images/style/logo.png" alt="logo">
		</div>
		    

	</div>
</div>	
<div id="navigation-menu">
    <div id="menu">
            <!--start -->

        <div id="nav">
            <ul>
              <li class="first">
               <a href="#">Home</a>

              </li>
              <li>
                <a href="#">Login</a>
              </li>
              <li>
                <a href="#">About</a>
               </li>


            </ul>
        </div>

    </div>  
        <!-- end-->	
</div>
   
<div id="container-contentother">
    <div id="inner-container">
        <div class="nav-menu">
            <ul>
            <li><a href="#intro">Introduction</a></li>
            <li><a href="#vision">Vision</a></li>
            <li><a href="#mission">Mission</a></li>
            <li><a href="#objectives">Objectives</a></li>
            <li><a href="#strategies">Strategies</a></li>
            </ul>
        </div>
         
        <div class="content">
            
        <?php echo $this->layout()->content; ?>
        </div>
    </div>
</div>
    

<div id="copyright">(C) Leapfrog Technology College, a college wing of Leapfrog Technology Inc.</div>


</body>
</html>
        