<!DOCTYPE html>
<head>
 <?php echo $this->headLink()->prependStylesheet($this->baseUrl('/css/style.css')); ?> 
   
</head>

<body>

<div id="header">
	<div id="title">
		<div id="logo">
			<img src="/images/style/logo.png" alt="logo">
                        EMS
		</div>
    

	</div>
</div>	
<div id="navigation-menu">
    <div id="menu">
            <!--start -->

        <div id="nav">
            <ul>
              <li class="first">
               <a href="#">Employees</a>

              </li>
              <li>
                <a href="#">Profile</a>
              </li>
              <li>
                <a href="<?php echo $this->baseUrl('/employee/attendance/history');?>">Attendance</a>
               </li>
              <li>
                <a href="<?php echo $this->baseUrl('front/index/logout');?>">Log Out</a>
               </li>    

            </ul>
        </div>

    </div>  
        <!-- end-->	
</div>
   
<div id="inner-container">
        <div class="nav-menu">
            <ul>
            <li><a href="<?php echo $this->baseUrl('/employee/index/index');?>">Employee Contacts</a></li>
            <li><a href="#">Show Profile</a></li>
            <li><a href="<?php echo $this->baseUrl('/employee/attendance/history');?>">Attendance History</a></li>
            <li><a href="<?php echo $this->baseUrl('/employee/attendance/check-in');?>">Check In</a></li>
            <li><a href="<?php echo $this->baseUrl('/employee/attendance/check-out');?>">Check Out</a></li>
            <li><a href="<?php echo $this->baseUrl('/employee/attendance/apply-leave');?>">Apply For Leave</a></li>
            
            </ul>
        </div>
         
        <div class="main-content">
            
        <?php echo $this->layout()->content; ?>
        </div>
 
</div>
<div style="clear:both;"></div>
    

<div id="copyright">&copy; Leapfrog Technology Inc.</div>


</body>
</html>
        