<head>
    <meta charset="utf-8" />
    <title>Leapfrog EMS - Apply for Leave</title>
    <link rel="stylesheet" href="/css/jquery-ui.css" />
    <script src="/jquery/jquery-1.9.1.js"></script>
    <script src="/jquery/jquery-ui.js"></script>
    <script>
        $(function() {
            $("#datepicker").datepicker();
            $("#datepicker2").datepicker();
            $( "#datepicker" ).datepicker( "option", "dateFormat", 'yy-mm-dd' );
            $( "#datepicker2" ).datepicker( "option", "dateFormat", 'yy-mm-dd' );
        });
    </script>
</head>
    <form method="post" action="">
      <h1>Apply for Leave</h1>
      <label>From date: </label><br>
      <input type="text" id="datepicker" required name="from_date" /><br>
            
      <label>To date:</label><br>
      <input type="text" id="datepicker2" required name="to_date"/><br>
      
      
      <label>Reason:</label><br>
      <textarea rows="3" cols="30" name="reason" required></textarea><br>
            <input class="button-form white" type="submit" name="submit" value="Apply">
    </form>
    