
<?php
    
    if($this->status == 'none')
    {
        echo "<h1>Check Out</h1>";
        echo $this->form;
    }
    else 
    {
        echo "<h3 style='font-size: x-large;'>Today <font color='green'>".$this->data['date']."</font>, You are Checked Out at <font color='green'>".$this->data['checkout_time']."</font></h3>";
        echo "<p><b>Status</b>: ".$this->data['checkout_status']."</p>";
        
        if($this->data['checkout_status'] == 'Early')
            echo "<p><b>Reason</b>: ".$this->data['checkout_comments']."</p>";
    }
?>