
<div class="nav-menu">
    
    <div class="subtitle"><h1>Login</h1></div>
    
    <div>
        <ul>
            <li><a href="/front/index/login">Home</a></li>
            <li><a href="/front/index/about">About</a></li>
        </ul>
    </div>
</div>

<div class="main-content">

    <p>
    Employee Management system is software for managing data of employees in a company.
    EMS comprises the personal details of an employee. 
    EMS keeps the record of employees joining date, leaving date.
    So we have decided to investigate the use of an Employee Management System. 
    This system would be used by HR Department of the corporation. 
    The purpose of this document is to analyze and elaborate on the high-level needs and features of the Employee Management System. 
    It focuses on the capabilities and facilities provided by accompany. 
    This project is well versed with the programming.
    Without an employee management system, it’s a tedious job for the Human Resource department of any company.
    The Employee Management System that is developed to provides the information of the employees and many other facilities.
    Employee Management system will store all the details of the employees.



</p>
</div>

