
<div class="nav-menu">
    
    <div class="subtitle"><h1>Login</h1></div>
    
    <div style="color: red;">
        <?php
        if ($this->missmatchmsg) {
            echo $this->missmatchmsg;
        }
        ?>
    </div>
    <div>
        <?php echo $this->loginfrm; ?>
    </div>
</div>

<div class="main-content">
    <img src="/images/front/funtime.jpg" alt="Members" width="95%" height="95%">
</div>