
<?php
        echo $this->headScript()->appendFile('/ckeditor/ckeditor.js');
?>
<div style="float:right;"><p><img src="/uploads/<?php echo $this->imageName; ?>" width="120px" 
height="70px"></p>
</div>

<div>
<?php echo $this->form; ?>
</div>

<script type="text/javascript">

    CKEDITOR.replace('info', {
        filebrowserBrowseUrl: '/ckfinder/ckfinder.html',
        filebrowserImageBrowseUrl: '/ckfinder/ckfinder.html?type=Images',
        filebrowserFlashBrowseUrl: '/ckfinder/ckfinder.html?type=Flash',
        filebrowserUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
        filebrowserImageUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
        filebrowserFlashUploadUrl: '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash',
        filebrowserWindowWidth: '500',
        filebrowserWindowHeight: '300'});

</script>
