<h1>Employee Contacts</h1>

<p>
<?php $data = $this->employeeRecords; ?>

    <table class='table-contacts'>
        <tr>
            <td>S.N.</td>
            <td>Full Name</td>
            <td>Designation</td>
            <td>Email Id</td>
            <td>Contact</td>                
        </tr>
    <?php

    $count = 0;
    foreach($data as $key=>$value)
    {
       echo"<tr>";
       echo"<td>".++$count."</td>
            <td>".$value['full_name']."</td>
            <td>".$value['designation']."</td>
            <td>".$value['email_id']."</td>
            <td>".$value['contact']."</td>";
       echo "</tr>";
    }
    //    echo "<pre>";
    //    print_r();
    //    echo "</pre>";
    ?>
    </table>
</p>