   
    <?php 
foreach ($this->user as $row):?>
    
<div style="float:right;">
    <p><img src="/uploads/<?php echo $row['image_name']?>" width="120px" 
height="70px"></p>
</div>
<div>
     <h3>Full Name:</h3>
    <p style="text-transform: capitalize;"><?php  echo $row['full_name'];?></p>
  
     <h3>Address:</h3>
     <p  style="text-transform: capitalize;"><?php echo $row['address'];?></p>
     
     <h3>Date of Birth</h3>
     <p><?php echo $row['DOB'];?></p>
     
     <h3>CV Information</h3>
     <p><?php echo $row['info'];?></p>
  
</div>
        
    <?php endforeach;?>
