
<?php
    $roles = $this->dataRoles;
    $resources = $this->dataResources;
?>

<h2>Assign Permissions</h2>

<form method="post" action="localhost" id="permissions">
    <div class="roles">
        <select id="roles" name="roles" style="width: 300px;" >
            <option value="">Select Roles</option>

             <?php        
                foreach ($roles as $value)
                {
                       echo "<option value='".$value['id']."'>".$value['name']."</option>";
                }

            ?>
        </select>
    </div>
    <br>
    <div class="resources">
        <select name="resources" style="width: 300px;" id="resources">
            <option value="">Select Resources</option>
             <?php        
                foreach ($resources as $value)
                {
                    echo "<option value='".$value['id']."'>".$value['description']."</option>";
                }
            ?>
        </select>

    </div>
    <br>
    <div class="actions">


    </div>
    <br>
    <div class="submit">
         <input type="button" name="submit" value="Assign Permission" class="button-form white submit"/>
    </div>
    
</form>

    
  <script src="/jquery/jquery-1.9.1.js"></script>
    <script src="/jquery/jquery-ui.js"></script>
    <script>
        $(function() {
            
            var actionList;
            
            $('#resources').attr('disabled',true);
           
            $('.actions').hide();
            $('.submit').hide();
            
            //When Roles select options is changed, resources is enabled
            $('#roles').change(function() {
                $('#resources').removeAttr('disabled');
            });
            
            
            //When Resources select options is changed, actions are shown
            $('#resources').change(function()
            {
                var resourceId = $('#resources').val();
                var roleId = $('#roles').val();
                
                $('.actions').empty();
                $.ajax({
                type: 'post',
                data: {resource: resourceId, role_id: roleId},
                url: '<?php echo $this->baseUrl(); ?>/admin/permission/getlist',
                dataType: 'json',
                success: function(data) {
                    
                 
                    actionList = data.actionList;
                    var permittedActionList = data.actionName;
                    var count = data.count;
                    
                    $('.actions').show();
                    $('.submit').show();
             
                      //exit();
                    $.each(actionList, function(key,value){
                            $('.actions').append('<ul><input type="checkbox" id ='+value['name'] + ' name="' + value['name'] + '" value="' + value['id'] + '" />' + value['name'] + '</ul>');
                  
                         
                    });
                    
                    for(i=0;i<count;i++)
                    {
                        $('#' + permittedActionList[i]['name']).attr('checked', true);
                    }
                    
                    
               
            
                   }
                });
                
                
                $('.submit').click(function() {
                    var actions = new Array();
                    var roleId = $('#roles').val();
                    var resourceId = $('#resources').val();
                    var count = 0;
                    
                    $.each(actionList, function(key,value){
                        if($('#'+value['name']).is(":checked"))
                        {
                            actions[count++] = value['name'];
                        }
                  
                         
                    });
                    
                    alert(roleId + " " + resourceId);
                    
                    console.log(actions);


//                    for (i = 0; i < countActions; i++) {
//                        if ($('#actionList-' + i).is(":checked")) {
//                            actions[i] = $('#actionList-' + i).attr('value');
//
//                        }
//                    }

            
                    $.ajax({
                        type: 'post',
                        data: {actionList: actions, roleId: roleId, resourcesId: resourceId},
                        url: '<?php echo $this->baseUrl(); ?>/admin/permission/edit-permission',
                        dataType: 'json',
                        cache: false,
                        success: function(data) {

                            var check = data.check;
                            if (check === 1) {
                                alert('success');
                            }
                            else {
                                alert('failure');
                            }
                            
                            return false;
                        }
                    });

                });
                 

            });
            
            
            
            
            
        });
    </script>