
<?php
    $roles = $this->dataRoles;
    $resources = $this->dataResources;
?>

<h2>Assign Permissions</h2>

<form method="post" action="localhost" id="permissions">
    <div class="roles">
        <select id="roles" name="roles" style="width: 300px;" >
            <option value="">Select Roles</option>

             <?php        
                foreach ($roles as $value)
                {
                       echo "<option value='".$value['id']."'>".$value['name']."</option>";
                }

            ?>
        </select>
    </div>
    <br>
    <div class="resources">
        <select name="resources" style="width: 300px;" id="resources">
            <option value="">Select Resources</option>
             <?php        
                foreach ($resources as $value)
                {
                    echo "<option value='".$value['id']."'>".$value['description']."</option>";
                }
            ?>
        </select>

    </div>
    <br>
    <div class="actions">


    </div>
    <br>
    <div class="submit">
         <input type="button" name="submit" value="Assign Permission" class="button-form white submit"/>
    </div>
    
</form>

    
  <script src="/jquery/jquery-1.9.1.js"></script>
    <script src="/jquery/jquery-ui.js"></script>
    <script>
        $(function() {
            $('#resources').attr('disabled',true);
           
            $('.actions').hide();
            $('.submit').hide();
            
            //When Roles select options is changed, resources is enabled
            $('#roles').change(function() {
                $('#resources').removeAttr('disabled');
            });
            
            
            //When Resources select options is changed, actions are shown
            $('#resources').change(function()
            {
                var resourceId = $('#resources').val();
                var roleId = $('#roles').val();
                
                $('.actions').empty();
                $.ajax({
                type: 'post',
                data: {resource: resourceId, role_id: roleId},
                url: '<?php echo $this->baseUrl(); ?>/admin/permission/getlist/',
                dataType: 'json',
                success: function(data) {
                    
                    var actionList = data.actionList;
                    var permittedActionList = data.permittedActionName;
                    
                    $('.actions').show();
                    $('.submit').show();
                    
                    $.each(actionList, function(key,value){
                            $('.actions').append('<ul><input type="checkbox" id ='+value['id'] + ' name="' + value['name'] + '" value="' + value['id'] + '" />' + value['name'] + '</ul>');
                    
                                 $.each()(permittedActionList, function(keyPermitted, valuePermitted){
                                     if(value['name'] == valuePermitted)
                                         $('#' + value['id']).attr('checked','checked');
                                 });
                    });
                    
                    
               
            
                   }
                });
                 

            });
            
            
        });
    </script>